apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-server
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: server
          env:
            - name: DBCONFIG_USER
              valueFrom:
                secretKeyRef:
                  name: katib-mysql-secrets
                  key: DBCONFIG_USER
            - name: DBCONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-pxc-db
                  key: root
