apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-server
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: server
          env:
            - $patch: replace
            - name: DBCONFIG_USER
              valueFrom:
                secretKeyRef:
                  key: DBCONFIG_USER
                  name: mysql-secret
            - name: DBCONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DBCONFIG_PASSWORD
                  name: mysql-secret
            - name: DBCONFIG_HOST_NAME
              valueFrom:
                secretKeyRef:
                  key: DBCONFIG_HOST
                  name: mysql-secret
            - name: DBCONFIG_PORT
              valueFrom:
                secretKeyRef:
                  key: DBCONFIG_PORT
                  name: mysql-secret
            - name: NAMESPACE_TO_WATCH
              value: ""
            - name: CACHE_IMAGE
              valueFrom:
                configMapKeyRef:
                  key: cacheImage
                  name: pipeline-install-config
            - name: CACHE_NODE_RESTRICTIONS
              valueFrom:
                configMapKeyRef:
                  key: cacheNodeRestrictions
                  name: pipeline-install-config
            - name: DBCONFIG_DRIVER
              value: mysql
            - name: DBCONFIG_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: cacheDb
                  name: pipeline-install-config
