apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-server
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: server
          env:
            - name: DBCONFIG_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DBCONFIG_USER
            - name: DBCONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DBCONFIG_PASSWORD
            - name: DBCONFIG_HOST_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DBCONFIG_HOST_NAME
            - name: DBCONFIG_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DBCONFIG_PORT
