apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-mysql
  namespace: kubeflow
$patch: delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: katib-mysql
  namespace: kubeflow
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: katib-mysql
  namespace: kubeflow
$patch: delete
---
apiVersion: v1
kind: Secret
metadata:
  name: katib-mysql-secrets
  namespace: kubeflow
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-db-manager
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: katib-db-manager
          env:
            - name: DB_NAME
              value: mysql
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DBCONFIG_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DBCONFIG_PASSWORD
            - name: KATIB_MYSQL_DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: KATIB_MYSQL_DB_DATABASE
            - name: KATIB_MYSQL_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DBCONFIG_HOST
            - name: KATIB_MYSQL_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DBCONFIG_PORT
