apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-grpc-deployment
spec:
  template:
    spec:
      containers:
        - name: container
          # Remove existing environment variables
          env:
          - $patch: replace
          envFrom:
          - configMapRef:
              name: metadata-grpc-configmap
          args: ["--grpc_port=$(METADATA_GRPC_SERVICE_PORT)",
                 "--mysql_config_host=metadata-cluster-mysql-master.dkube-infra.svc.cluster.local",
                 "--mysql_config_database=metadb",
                 "--mysql_config_port=3306",
                 "--mysql_config_user=root",
                 "--mysql_config_password=test"]
