apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-grpc-deployment
spec:
  template:
    spec:
      containers:
        - name: container
          # Remove existing environment variables
          env:
          - $patch: replace
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "true"
          - name: DBCONFIG_USER
            valueFrom:
                secretKeyRef:
                  name: katib-mysql-secrets
                  key: DBCONFIG_USER
          - name : DBCONFIG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-db-pxc-db
                key: root
          envFrom:
          - configMapRef:
              name: metadata-grpc-configmap
          args: ["--grpc_port=$(METADATA_GRPC_SERVICE_PORT)",
                 "--mysql_config_host=metadata-db",
                 "--mysql_config_database=metadb",
                 "--mysql_config_port=3306",
                 "--mysql_config_user=$(DBCONFIG_USER)",
                 "--mysql_config_password=$(DBCONFIG_PASSWORD)"]
