apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: kubeflow
$patch: delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: kubeflow
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: kubeflow
$patch: delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql
  namespace: kubeflow
$patch: delete