apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: kubeflow
$patch: delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: kubeflow
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: kubeflow
$patch: delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql
  namespace: kubeflow
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: ml-pipeline-api-server
          env:
            - $patch: replace
            - name: DBCONFIG_USER
              valueFrom:
                secretKeyRef:
                  key: DBCONFIG_USER
                  name: mysql-secret
            - name: DBCONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DBCONFIG_PASSWORD
                  name: mysql-secret
            - name: DBCONFIG_HOST
              valueFrom:
                secretKeyRef:
                  key: DBCONFIG_HOST
                  name: mysql-secret
            - name: DBCONFIG_PORT
              valueFrom:
                secretKeyRef:
                  key: DBCONFIG_PORT
                  name: mysql-secret
            - name: KUBEFLOW_USERID_HEADER
              value: kubeflow-userid
            - name: KUBEFLOW_USERID_PREFIX
              value: ""
            - name: AUTO_UPDATE_PIPELINE_DEFAULT_VERSION
              valueFrom:
                configMapKeyRef:
                  key: autoUpdatePipelineDefaultVersion
                  name: pipeline-install-config
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OBJECTSTORECONFIG_SECURE
              value: "false"
            - name: OBJECTSTORECONFIG_BUCKETNAME
              valueFrom:
                configMapKeyRef:
                  key: bucketName
                  name: pipeline-install-config
            - name: DBCONFIG_DBNAME
              valueFrom:
                configMapKeyRef:
                  key: pipelineDb
                  name: pipeline-install-config
            - name: DBCONFIG_CONMAXLIFETIMESEC
              valueFrom:
                configMapKeyRef:
                  key: ConMaxLifeTimeSec
                  name: pipeline-install-config
            - name: OBJECTSTORECONFIG_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  key: accesskey
                  name: mlpipeline-minio-artifact
            - name: OBJECTSTORECONFIG_SECRETACCESSKEY
              valueFrom:
                secretKeyRef:
                  key: secretkey
                  name: mlpipeline-minio-artifact
