apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: kubeflow
$patch: delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: kubeflow
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: kubeflow
$patch: delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql
  namespace: kubeflow
$patch: delete
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: kubeflow
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: ml-pipeline-api-server
          env:
            - name: DBCONFIG_USER
              valueFrom:
                secretKeyRef:
                  name: katib-mysql-secrets
                  key: DBCONFIG_USER
            - name: DBCONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-pxc-db
                  key: root
